config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  devise_for :users, :skip => [:registrations], controllers: { confirmations: 'confirmations' }
  as :user do
    get 'users/sign_up' => 'devise/registrations#new', :as => 'new_user_registration'
    post 'users' => 'devise/registrations#create', :as => 'user_registration'
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration_update'
    delete 'users' => 'devise/registrations#destroy', :as => 'user_registration_destroy'
  end

  resources :categories do
    resources :subcategories
  end

  resources :questions do
    resources :answers, only: [:create, :update, :destroy] do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      post 'pick', to: 'answers#pick'
    end
  end
  resources :communities do
    get 'search', on: :member
    resources :memberships
    resources :posts do
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' }
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
    resources :events do
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' }
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      post 'favorite', to: 'favorites#create'
      delete 'unfavorite', to: 'favorites#destroy'
    end
  end

  resources :users, only: [] do
    resources :diaries do
      collection do
        get :my_diaries
      end
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'diary' }
    end
  end


  resources :pets do
    member do
      post :set_profile_display
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :admin do
    root to: 'admins#pets', as: :admin_root
  end
  root "users#my_page"
  get "my_diaries", to: "diaries#my_diaries"
  get "my_pets", to: "pets#my_pets"
  get "my_communities", to: "communities#my_communities"
  get "my_questions", to: "questions#my_questions"
  resources :users, only: [:show] do
    member do
      get :confirm_email
    end
  end
  resources :friend_requests, only: [:create] do
    member do
      put :accept
      delete :reject
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :messages, only: [:create, :show, :index] do
    member do
      patch :mark_as_read
    end
  end

  resources :comments, path: "community/:community_id/comments/", only: [:show]

  resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' } do
    resources :comments, only: [:create, :destroy, :show], defaults: { commentable: 'comment' } do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :visits, only: [:index] do
    get 'read', to: 'visits#read'
  end
  resources :prohibited_words, except: [:show]
  resources :admin_messages

  get 'friendrequest_sent/:id', to: 'friend_requests#sent', as: 'friendrequest_sent'

  get "notifications", to: "notifications#index"
  get "my_page", to: "users#my_page"
  get 'all_content', to: 'all_content#index'
  get "/admin/posts", to: "admins#posts"
  get "/admin/communities", to: "admins#communities"
  get "/admin/events", to: "admins#events"
  get "/admin/users", to: "admins#users"
  get "/admin/diaries", to: "admins#diaries"
  get "/admin/pets", to: "admins#pets"
  get "/admin/categories", to: "admins#categories"
  get "/admin/prohibited_words", to: "admins#prohibited_words"
  get "/admin/messages", to: "admins#messages", as: "admin_notifications"

  get "/my_events", to: "events#my_events"
  get "/all_events", to: "events#all_events"
  get "/all_posts", to: "posts#all_posts"
  get "/my_posts", to: "posts#my_posts"
  get "/confirmation_page", to: "home#confirmation", as: "confirmation_page"
  get "/notification/:id", to: "notifications#mark_as_read", as: "notification"

  get '/additional_info', to: 'users#additional_info'
  post '/save_additional_info', to: 'users#save_additional_info'

  get '/edit_community_image/:id', to: 'communities#edit_community_image', as: 'edit_community_image'
  get '/edit_post_image/:id', to: 'posts#edit_post_image', as: 'edit_post_image'
  get '/edit_event_image/:id', to: 'events#edit_event_image', as: 'edit_event_image'

  
  get "company", to: "company#index"
  get "terms", to: "terms#index"
  get "policy", to: "policy#index"
  get "regarding", to: "regarding#index"
  get "contact", to: "contact#index"
end

app/views/admins/_sidebar.html.erb
<!-- _sidebar.html.erb -->
<aside class="sidebar-panel">
  <ul class="">
    <li class="sidebar-item">
      <%= link_to "オーナー", admin_users_path, class: "nav-link" %>
    </li>
    <li class="sidebar-item">
      <%= link_to "ペット", admin_pets_path, class: "nav-link" %>
    </li>
    <li class="sidebar-item">
      <%= link_to "コミュニティ", admin_communities_path, class: "nav-link" %>
    </li>
    <li class="sidebar-item">
      <%= link_to "トピック", admin_posts_path, class: "nav-link" %>
    </li>
    <li class="sidebar-item">
      <%= link_to "イベント", admin_events_path, class: "nav-link" %>
    </li>
    <li class="sidebar-item">
      <%= link_to "日記", admin_diaries_path, class: "nav-link" %>
    </li>
    <li class="sidebar-item">
      <%= link_to "ペットカテゴリー", admin_categories_path, class: "nav-link" %>
    </li>
    <li class="sidebar-item">
      <%= link_to "キーワード制限", admin_prohibited_words_path, class: "nav-link" %>
    </li>
    <li class="sidebar-item">
      <%= link_to "運営からのメッセージ", admin_notifications_path, class: "nav-link" %>
    </li>
  </ul>
</aside>

app/views/admins/categories.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class="col-9">
      <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> ペットカテゴリー</h3>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>カテゴリー名</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td>
                <a href="<%= category_path(category) %>" class="btn bg-light-cyan text-white">詳細</a>
                <a href="<%= edit_category_path(category) %>" class="btn bg-main text-white ">編集</a>
                <a href="<%= category_path(category) %>" data-confirm="Are you sure?" data-method="delete" class="btn btn-secondary">削除</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/communities.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class= "col-9">
      <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> コミュニティ</h3>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>コミュニティ名</th>
            <th>オーナー</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @communities.each do |community| %>
            <tr>
              <td><%= community.title %></td>
              <td><%= community.admin.name %></td>
              <td>
                <a href="<%= community_path(community) %>" class="btn bg-light-cyan text-white">詳細</a>
                <a href="<%= edit_community_path(community) %>" class="btn bg-main text-white ">編集</a>
                <a href="<%= community_path(community) %>" data-confirm="Are you sure?" data-method="delete" class="btn btn-secondary">削除</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/diaries.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class= "col-9">
      <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> 日記</h3>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>オーナー</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @diaries.each do |diary| %>
            <tr>
              <td><%= diary.title %></td>
              <td><%= diary.user.name %></td>
              <td>
                <a href="<%= user_diary_path(diary.user, diary) %>" class="btn bg-light-cyan text-white">詳細</a>
                <a href="<%= edit_user_diary_path(diary.user, diary) %>" class="btn bg-main text-white ">編集</a>
                <a href="<%= user_diary_path(diary.user, diary) %>" data-confirm="Are you sure?" data-method="delete" class="btn btn-secondary">削除</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/events.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class= "col-9">
      <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> イベント</h3>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>イベント名</th>
            <th>主催者</th>
            <th>コミュニティ名</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.title %></td>
              <td><%= event.user.name %></td>
              <td><%= event.community.title %></td>
              <td>
                <a href="<%= community_event_path(event.community, event) %>" class="btn bg-light-cyan text-white">詳細</a>
                <a href="<%= edit_community_event_path(event.community, event) %>" class="btn bg-main text-white ">編集</a>
                <a href="<%= community_event_path(event.community, event) %>" data-confirm="Are you sure?" data-method="delete" class="btn btn-secondary">削除</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/messages.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class= "col-9">
      <div class="d-flex justify-content-between align-items-center">
        <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> メッセージ</h3>
        <%= form_with model: AdminMessage.new, url: admin_messages_path, remote: true do |form| %>
          <div class="input-group mb-0">
            <%= form.text_field :content, class: "form-control" %>
            <div class="input-group-btn">
              <%= form.submit '保存する', class: "btn bg-main text-white fw-bold" %>
            </div>
          </div>
        <% end %>
      </div>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>メッセージ</th>
            <th>送信日</th>
          </tr>
        </thead>
        <tbody>
          <% @admin_messages.each do |admin_message| %>
            <tr>
              <td><%= admin_message.content %></td>
              <td><%= admin_message.created_at %></td>
              <td><%= link_to "削除", admin_message_path(admin_message), method: :delete, class: "btn btn-secondary"  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/pets.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class= "col-9">
      <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> ペット</h3>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>ペット</th>
            <th>オーナー</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @pets.each do |pet| %>
            <tr>
              <td><%= pet.name %></td>
              <td><%= pet.user ? pet.user.name : "退会したユーザー" %></td>
              <td>
                <a href="<%= pet_path(pet) %>" class="btn bg-light-cyan text-white">詳細</a>
                <a href="<%= edit_pet_path(pet) %>" class="btn bg-main text-white ">編集</a>
                <a href="<%= pet_path(pet) %>" data-confirm="Are you sure?" data-method="delete" class="btn btn-secondary">削除</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/posts.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class= "col-9">
      <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> トピック</h3>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>トピック名</th>
            <th>作成者</th>
            <th>コミュニティ名</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.title %></td>
              <td><%= post.user.name %></td>
              <td><%= post.community.title %></td>
              <td>
                <a href="<%= community_post_path(post.community, post) %>" class="btn bg-light-cyan text-white">詳細</a>
                <a href="<%= edit_community_post_path(post.community, post) %>" class="btn bg-main text-white ">編集</a>
                <a href="<%= community_post_path(post.community, post) %>" data-confirm="Are you sure?" data-method="delete" class="btn btn-secondary">削除</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/prohibited_words.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class= "col-9">
      <div class="d-flex justify-content-between aling-items-end">
        <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> キーワード制限</h3>
        <%= form_with model: ProhibitedWord.new, url: prohibited_words_path, remote: true do |form| %>
          <div class="input-group mb-0">
            <%= form.text_field :word, class: "form-control" %>
            <div class="input-group-btn">
              <%= form.submit '追加する', class: "btn bg-main text-white fw-bold" %>
            </div>
          </div>
        <% end %>
      </div>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>制限ワード</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @prohibited_words.each do |prohibited_word| %>
            <tr>
              <td><%= prohibited_word.word %></td>
              <td>
                <a href="<%= edit_prohibited_word_path(prohibited_word) %>" class="btn bg-main text-white ">編集</a>
                <a href="<%= prohibited_word_path(prohibited_word) %>" data-confirm="Are you sure?" data-method="delete" class="btn btn-secondary">削除</a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/users.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-3">
      <%= render partial: "sidebar" %>
    </div>
    <div class= "col-9">
      <h3 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> オーナー</h3>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>氏名</th>
            <th>メールアドレス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>