config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  devise_for :users, :skip => [:registrations], controllers: { confirmations: 'confirmations' }
  as :user do
    get 'users/sign_up' => 'devise/registrations#new', :as => 'new_user_registration'
    post 'users' => 'devise/registrations#create', :as => 'user_registration'
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration_update'
    delete 'users' => 'devise/registrations#destroy', :as => 'user_registration_destroy'
  end

  resources :categories do
    resources :subcategories
  end

  resources :questions do
    resources :answers, only: [:create, :update, :destroy] do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      post 'pick', to: 'answers#pick'
    end
  end
  resources :communities do
    get 'search', on: :member
    resources :memberships
    resources :posts do
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' }
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
    resources :events do
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' }
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      post 'favorite', to: 'favorites#create'
      delete 'unfavorite', to: 'favorites#destroy'
    end
  end

  resources :users, only: [] do
    resources :diaries do
      collection do
        get :my_diaries
      end
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'diary' }
    end
  end


  resources :pets do
    member do
      post :set_profile_display
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :admin do
    root to: 'admins#pets', as: :admin_root
  end
  root "users#my_page"
  get "my_diaries", to: "diaries#my_diaries"
  get "my_pets", to: "pets#my_pets"
  get "my_communities", to: "communities#my_communities"
  get "my_questions", to: "questions#my_questions"
  resources :users, only: [:show] do
    member do
      get :confirm_email
    end
  end
  resources :friend_requests, only: [:create] do
    member do
      put :accept
      delete :reject
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :messages, only: [:create, :show, :index] do
    member do
      patch :mark_as_read
    end
  end

  resources :comments, path: "community/:community_id/comments/", only: [:show]

  resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' } do
    resources :comments, only: [:create, :destroy, :show], defaults: { commentable: 'comment' } do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :visits, only: [:index] do
    get 'read', to: 'visits#read'
  end
  resources :prohibited_words, except: [:show]
  resources :admin_messages

  get 'friendrequest_sent/:id', to: 'friend_requests#sent', as: 'friendrequest_sent'

  get "notifications", to: "notifications#index"
  get "my_page", to: "users#my_page"
  get 'all_content', to: 'all_content#index'
  get "/admin/posts", to: "admins#posts"
  get "/admin/communities", to: "admins#communities"
  get "/admin/events", to: "admins#events"
  get "/admin/users", to: "admins#users"
  get "/admin/diaries", to: "admins#diaries"
  get "/admin/pets", to: "admins#pets"
  get "/admin/categories", to: "admins#categories"
  get "/admin/prohibited_words", to: "admins#prohibited_words"
  get "/admin/messages", to: "admins#messages", as: "admin_notifications"

  get "/my_events", to: "events#my_events"
  get "/all_events", to: "events#all_events"
  get "/all_posts", to: "posts#all_posts"
  get "/my_posts", to: "posts#my_posts"
  get "/confirmation_page", to: "home#confirmation", as: "confirmation_page"
  get "/notification/:id", to: "notifications#mark_as_read", as: "notification"

  get '/additional_info', to: 'users#additional_info'
  post '/save_additional_info', to: 'users#save_additional_info'

  get '/edit_community_image/:id', to: 'communities#edit_community_image', as: 'edit_community_image'
  get '/edit_post_image/:id', to: 'posts#edit_post_image', as: 'edit_post_image'
  get '/edit_event_image/:id', to: 'events#edit_event_image', as: 'edit_event_image'

  
  get "company", to: "company#index"
  get "terms", to: "terms#index"
  get "policy", to: "policy#index"
  get "regarding", to: "regarding#index"
  get "contact", to: "contact#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications
  end

  def mark_as_read
    @notification = Notification.find(params[:id])
    @notification.mark_as_read!
    redirect_to @notification.to_notification.url
  end
end

app/views/notifications/_notification.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 col-lg-3">
      <%= render "shared/sidebar", current_page: 'notifications' %>
    </div>
    <div class="col-12 col-lg-9 communities">
      <div class="mb-5">
        <h4 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-light-main"></i> 通知一覧</h4>
        <div class="mt-4">
          <div class="border rounded">
            <div class="border-bottom px-3 py-2">
              <small class="d-flex justify-content-between align-items-center">
                <span>未談件数:<%= current_user.notifications.unread.count %></span>
                <span>1件~<%= notifications.count %>件を表示</span>
              </small>
            </div>
            <% notifications.each do |notification| %>
                <div class="px-3 py-2 d-flex justify-content-between border-bottom align-items-center">
                  <div class="d-flex align-items-center gap-2">
                    <% if notification.read_at %>
                      <i class="far fa-envelope-open"></i>
                    <% elsif %>
                      <i class="far fa-envelope"></i>
                    <% end %> <span class="text-decoration-underline">
                      <%= link_to notification.to_notification.message, notification_path(notification), class: "text-black" %>
                    </span>
                  </div>
                  <span><%= notification.created_at.strftime('%m月%d日 %H:%M') %></span>
                </div>
            <% end %>
            <div class="px-3 py-2 d-flex justify-content-center align-items-center">
              <ul class="d-flex justify-content-center align-items-center gap-2">
                <li>&lt;</li>
                <li>1</li>
                <li>2</li>
                <li>3</li>
                <li>...</li>
                <li>7</li>
                <li>&gt;</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <%
=begin%>
 <div class="mb-5">
        <h4 class="d-flex align-items-center gap-2 fw-bold"><i class="fa fa-paw text-main"></i> メッセージ一覧</h4>
        <div class="mt-4">
          <div class="border rounded">
            <div class="border-bottom px-3 py-2">
              <small class="d-flex justify-content-between align-items-center">
                <span>未談件数:2</span>
                <span>1件~4件を表示</span>
              </small>
            </div>
            <% messages.each do |message| %>
              <div class="px-3 py-2 d-flex justify-content-between border-bottom align-items-center">
                <div class="d-flex align-items-center gap-2">
                  <i class="fa fa-comment"></i> <span class="text-decoration-underline">
                    <p><%= link_to display_pet_or_username(message.sender), message_path(message) %>: <%= message.text %></p>
                  </span>
                </div>
                <span><%= message.created_at.strftime('%m月%d日 %H:%M') %></span>
              </div>
            <% end %>
            <div class="px-3 py-2 d-flex justify-content-center align-items-center">
              <ul class="d-flex justify-content-center align-items-center gap-2">
                <li>&lt;</li>
                <li>1</li>
                <li>2</li>
                <li>3</li>
                <li>...</li>
                <li>7</li>
                <li>&gt;</li>
              </ul>
            </div>
          </div>
        </div>
      </div> 
<%
=end%>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<%= render "notifications/notification", notifications: @notifications %>