config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  devise_for :users, :skip => [:registrations], controllers: { confirmations: 'confirmations' }
  as :user do
    get 'users/sign_up' => 'devise/registrations#new', :as => 'new_user_registration'
    post 'users' => 'devise/registrations#create', :as => 'user_registration'
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration_update'
    delete 'users' => 'devise/registrations#destroy', :as => 'user_registration_destroy'
  end

  resources :categories do
    resources :subcategories
  end

  resources :questions do
    resources :answers, only: [:create, :update, :destroy] do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      post 'pick', to: 'answers#pick'
    end
  end
  resources :communities do
    get 'search', on: :member
    resources :memberships
    resources :posts do
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' }
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
    resources :events do
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' }
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      post 'favorite', to: 'favorites#create'
      delete 'unfavorite', to: 'favorites#destroy'
    end
  end

  resources :users, only: [] do
    resources :diaries do
      collection do
        get :my_diaries
      end
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'diary' }
    end
  end


  resources :pets do
    member do
      post :set_profile_display
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :admin do
    root to: 'admins#pets', as: :admin_root
  end
  root "users#my_page"
  get "my_diaries", to: "diaries#my_diaries"
  get "my_pets", to: "pets#my_pets"
  get "my_communities", to: "communities#my_communities"
  get "my_questions", to: "questions#my_questions"
  resources :users, only: [:show] do
    member do
      get :confirm_email
    end
  end
  resources :friend_requests, only: [:create] do
    member do
      put :accept
      delete :reject
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :messages, only: [:create, :show, :index] do
    member do
      patch :mark_as_read
    end
  end

  resources :comments, path: "community/:community_id/comments/", only: [:show]

  resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' } do
    resources :comments, only: [:create, :destroy, :show], defaults: { commentable: 'comment' } do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :visits, only: [:index] do
    get 'read', to: 'visits#read'
  end
  resources :prohibited_words, except: [:show]
  resources :admin_messages

  get 'friendrequest_sent/:id', to: 'friend_requests#sent', as: 'friendrequest_sent'

  get "notifications", to: "notifications#index"
  get "my_page", to: "users#my_page"
  get 'all_content', to: 'all_content#index'
  get "/admin/posts", to: "admins#posts"
  get "/admin/communities", to: "admins#communities"
  get "/admin/events", to: "admins#events"
  get "/admin/users", to: "admins#users"
  get "/admin/diaries", to: "admins#diaries"
  get "/admin/pets", to: "admins#pets"
  get "/admin/categories", to: "admins#categories"
  get "/admin/prohibited_words", to: "admins#prohibited_words"
  get "/admin/messages", to: "admins#messages", as: "admin_notifications"

  get "/my_events", to: "events#my_events"
  get "/all_events", to: "events#all_events"
  get "/all_posts", to: "posts#all_posts"
  get "/my_posts", to: "posts#my_posts"
  get "/confirmation_page", to: "home#confirmation", as: "confirmation_page"
  get "/notification/:id", to: "notifications#mark_as_read", as: "notification"

  get '/additional_info', to: 'users#additional_info'
  post '/save_additional_info', to: 'users#save_additional_info'

  get '/edit_community_image/:id', to: 'communities#edit_community_image', as: 'edit_community_image'
  get '/edit_post_image/:id', to: 'posts#edit_post_image', as: 'edit_post_image'
  get '/edit_event_image/:id', to: 'events#edit_event_image', as: 'edit_event_image'

  
  get "company", to: "company#index"
  get "terms", to: "terms#index"
  get "policy", to: "policy#index"
  get "regarding", to: "regarding#index"
  get "contact", to: "contact#index"
end

app/views/shared/_admin_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary p-3">
  <div class="container-fluid">
    <div class="container d-flex justify-content-start align-items-center gap-3">
      <a class="navbar-brand" href="#">
        <%= image_tag("logo.png", alt: "Logo", width: "230") %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav me-4 mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= admin_pets_path %>">管理画面</a>
          </li>
          <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "アカウント管理", edit_admin_registration_path, class: "nav-link active"  %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link active btn text-white bg-light-main ml-4"  %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_footer.html.erb
<div class="">
  <a id="back-to-top-button" aria-current="page" href="">
    <div class="position-fixed top-button bg-main text-white fw-bold d-flex flex-column justify-content-center align-items-center">
      <i class="fas fa-chevron-up fa-lg"></i>
      <span class="" style="font-size: smaller !important">トップへ</span>
    </div>
  </a>
</div>

<div class="mt-4">
  <div class="py-5 bg-light-yellow d-flex justify-content-center align-items-center flex-column gap-4">
    <img src="/images/logo.png" class="" style="width: 300px;"/>
    <div class="text-main">ペットSNS交流・情報交換サイト</div>
    <div class="d-flex justify-content-center align-items-center gap-3 mt-4">
      <a>運営会社</a>|
      <a>利用規約</a>|
      <a>プライバシーポリシー</a>|
      <a>特定商取引に関する表記</a>|
      <a>お問い合わせ</a>
    </div>
  </div>
  <div class="bg-main py-1">
    <div class="container-fluid text-white text-center">
      ©2023 Petter.ALL RIGHTS RESERVED.
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg nav-shadow flex-column p-0 bg-transparent">
  <div class="bg-main py-1 text-white w-100">
    <div class="container">
      <small>犬・猫の病気・けが しつけ・介護・食事などの悩みをみんなで解決しよう (仮テキスト)</small>
    </div>
  </div>
  <div class="container py-2 bg-white">
    <div class="d-flex justify-content-start align-items-center gap-3">
      <a class="navbar-brand" href="<%= my_page_path %>">
        <img src="/images/logo.png" alt="Logo" style="width: 230px">
      </a>
      <div style="width: 200px">
        <%= form_tag(pets_path, method: :get, class: "input-group border border-dark rounded") do %>
          <%= text_field_tag :search, params[:search], placeholder: "ペットを探す", class: "form-control" %>
          <div class="input-group-btn fw-bold">
            <button class="btn bg-transparent fw-bold" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        <% end %>
      </div>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav me-4 mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= communities_path %>">コミュニティ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= all_events_path%>">イベント</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= all_posts_path %>">トピック</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= questions_path %>">Q&A</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link active ml-2" aria-current="page" href="<%= notifications_path %>">
              <div class="position-relative">
                <i class="far fa-bell fa-lg"></i>
                <% if current_user.notifications.unread.count > 0 %>
                <span class="position-absolute rounded-circle d-flex justify-content-center align-items-center top-50 start-50 text-white fw-bold bg-main" style="width: 20px; height: 20px; font-size: smaller !important"><%= current_user.notifications.unread.count %></span>
                <% end %>
              </div>
            </a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link active ml-2" aria-current="page" href="<%= notifications_path %>">
              <div class="position-relative">
                <i class="far fa-envelope fa-lg"></i>
                <% if current_user.messagee.unread.count > 0 %>
                <span class="position-absolute rounded-circle d-flex justify-content-center align-items-center top-50 start-50 text-white fw-bold bg-main" style="width: 20px; height: 20px; font-size: smaller !important"><%= current_user.messagee.unread.count %></span>
                <% end %>
              </div>
            </a>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link active btn text-white bg-light-main ml-4"  %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "会員登録", new_user_registration_path, class: "nav-link active btn text-white bg-light-main ml-4"  %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link active btn text-white bg-light-main ml-4"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="sidebar-container">
  <div class="px-4 py-4 bg-main rounded ">
    <div class="px-4 py-4 bg-light rounded fw-bold text-center">
      <h4 class="text-center fw-bold mb-4">
        <%= link_to display_pet_or_username(current_user)+"さま", user_path(current_user), class: "mb-4 text-black" %>  
      </h4>
      <div class="mt-2 bg-white py-3">
        <div class="text-center mb-3">お知らせ</div>
        <div class=" d-flex align-items-center flex-column gap-2">
          <div class="d-flex gap-2 align-items-center">
            <a class="text-black" aria-current="page" href="<%= notifications_path %>">
              <i class="far fa-bell fa-lg"></i> 
              通知:<%= current_user.notifications.unread.count %>件
            </a>
          </div>
          <div class="d-flex gap-2 align-items-center">
            <a class="text-black" aria-current="page" href="<%= messages_path %>">
              <i class="far fa-envelope fa-lg"></i> 
              メール:<%= current_user.messagee.unread.count %>件
            </a>
          </div>
        </div>
      </div>
    </div>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-lg w-100 btn-block text-main fw-bold py-3 bg-white mt-3"  %>
  </div>
  <div class="text-center py-4">
    <div class="d-flex fw-bold text-main justify-content-center gap-2 align-items-center">
      <%= link_to "", class: "text-main fw-bold text-decoration-none" do %>
        <i class="fas fa-user-friends fa-lg fa-flip-horizontal"></i> 友達リクエスト<%= current_user.received_friend_requests.count %>件
      <% end %>
    </div>
  </div>
  <div>
    <a class="d-flex justify-content-center gap-1 align-items-center bg-normal-yellow text-white py-3 btn w-100 fw-bold" href="<%= new_user_diary_path(current_user) %>">
      <i class="fas fa-pencil-alt"></i> 日記を書く
    </a>
    <div class="mt-3 text-center d-flex justify-content-center gap-2 align-items-center">
      <%= link_to visits_path, class: "clr-black text-black font-18" do %>
        <i class="fas fa-paw" style="transform: rotateZ(45deg);"></i> <span>訪問回数:</span> <span><%= Visit.where(visited_id: current_user.id, created_at: Time.zone.today.all_day).unread.count %>回</span>
      <% end %>
    </div>
  </div>
  <% if current_page && current_page == 'diary' %>
  <div class="border-bottom border-2 border-bottom-dashed-grey mt-3 mb-3 py-3">
    <% today = Date.today %>
    <div class="mb-3">
      <div class="card-body">
        <h5 class="card-title text-center mb-2"><%= today.strftime('%Y年%m月') %></h5>
        <% first_day_of_month = today.at_beginning_of_month %>
        <% last_day_of_month = today.at_end_of_month %>
        <% first_day_of_calendar = first_day_of_month.beginning_of_week(:sunday) %>
        <% last_day_of_calendar = last_day_of_month.end_of_week(:monday) %>
      
        <div class="d-flex justify-content-evenly align-items-center" style="background-color: #DBEDFB !important; ">
          <div class="no-wrap border border-light-grey w-100 text-center">日</div>
          <div class="no-wrap border border-light-grey w-100 text-center">月</div>
          <div class="no-wrap border border-light-grey w-100 text-center">火</div>
          <div class="no-wrap border border-light-grey w-100 text-center">水</div>
          <div class="no-wrap border border-light-grey w-100 text-center">木</div>
          <div class="no-wrap border border-light-grey w-100 text-center">金</div>
          <div class="no-wrap border border-light-grey w-100 text-center">土</div>
        </div>
          
        <% first_day_of_calendar.step(last_day_of_calendar, 1).each_slice(7) do |week| %>
          <div class="d-flex justify-content-evenly align-items-center">
            <% week.each do |day| %>
              <div class="no-wrap border border-light-grey w-100 text-center <%= day.month == today.month && current_user.has_diary_in?(day.year, day.month, day.day) ? 'bg-light-yellow' : '' %>">
                <% if day.month == today.month %>
                  <% if current_user.has_diary_in?(day.year, day.month, day.day) %>
                    <%= link_to day.day, my_diaries_path(year: day.year, month: day.month, day: day.day) %>
                  <% else %>
                    <%= day.day.to_s.rjust(2, '0') %>
                  <% end %>
                <% else %>
                  &nbsp;
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <% current_user.diary_years.each do |year| %>
      <h6 class="pb-2 fw-bold text-light-main border-bottom border-2 border-light-main">過去の日記</h6>
      <div class="small-font no-wrap">
        <div class="card-body">
          <h5 class="card-title text-center"><%= year %>年</h5>
          <% (1..12).each_slice(4) do |quarter| %>
            <div class="d-flex justify-content-evenly align-items-center">
              <% quarter.each do |month| %>
                <div class="">
                  <% if current_user.has_diary_in?(year, month) %>
                    <%= link_to "#{month}月", my_diaries_path(year: year, month: month) %>
                  <% else %>
                    <%= "#{month}月" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
  <div class="mt-5">
    <div class="d-flex align-items-center gap-2 fw-bold">
      <i class="fa fa-search"></i>  ペットを探す
    </div>
    <%= form_tag(pets_path, method: :get, class: "input-group border border-dark rounded mt-2") do %>
      <%= text_field_tag :search, params[:search], placeholder: "例：ヨークシャーテリア", class: "form-control" %>
      <div class="input-group-btn fw-bold">
        <button class="btn bg-transparent fw-bold" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </div>
    <%end%>
  </div>
  <div class="mt-4 sidebar-panel">
    <h6 class="pb-2 fw-bold text-light-main border-bottom border-2 border-light-main">サービス</h6>
    <div class="mt-4">
      <ul class="">
        <li class="sidebar-item">
          <%= link_to "Myコミュニティ一覧", my_communities_path %>
        </li>
        <li class="sidebar-item">
          <%= link_to "Myイベント一覧", my_events_path %>
        </li>
        <li class="sidebar-item">
          <%= link_to "コミュニティ一覧", communities_path %>
        </li>
        <li class="sidebar-item">
          <%= link_to "トピック一覧", all_posts_path %>
        </li>
        <li class="sidebar-item">
          <%= link_to "イベント一覧", all_events_path %>
        </li>
        <li class="sidebar-item">
          <%= link_to "日記", my_diaries_path %>
        </li>
        <li class="sidebar-item">
          <%= link_to "Q&A", questions_path %>
        </li>
      </ul>
    </div>
  </div>
  <div class="mt-4 sidebar-panel">
    <h6 class="pb-2 fw-bold text-light-main border-bottom border-2 border-light-main">設定</h6>
    <div class="">
      <ul class="">
        <li class="sidebar-item">
          <%= link_to "会員情報変更", edit_user_registration_path %>
        </li>
        <li class="sidebar-item">
          <%= link_to "ペット情報変更", my_pets_path %>
        </li>
        <li class="sidebar-item">
          <%= link_to "設定変更", root_path %>
        </li>
      </ul>
    </div>
  </div>
</div>