config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  devise_for :users, :skip => [:registrations], controllers: { confirmations: 'confirmations' }
  as :user do
    get 'users/sign_up' => 'devise/registrations#new', :as => 'new_user_registration'
    post 'users' => 'devise/registrations#create', :as => 'user_registration'
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration_update'
    delete 'users' => 'devise/registrations#destroy', :as => 'user_registration_destroy'
  end

  resources :categories do
    resources :subcategories
  end

  resources :questions do
    resources :answers, only: [:create, :update, :destroy] do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      post 'pick', to: 'answers#pick'
    end
  end
  resources :communities do
    get 'search', on: :member
    resources :memberships
    resources :posts do
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' }
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
    resources :events do
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' }
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      post 'favorite', to: 'favorites#create'
      delete 'unfavorite', to: 'favorites#destroy'
    end
  end

  resources :users, only: [] do
    resources :diaries do
      collection do
        get :my_diaries
      end
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'diary' }
    end
  end


  resources :pets do
    member do
      post :set_profile_display
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :admin do
    root to: 'admins#pets', as: :admin_root
  end
  root "users#my_page"
  get "my_diaries", to: "diaries#my_diaries"
  get "my_pets", to: "pets#my_pets"
  get "my_communities", to: "communities#my_communities"
  get "my_questions", to: "questions#my_questions"
  resources :users, only: [:show] do
    member do
      get :confirm_email
    end
  end
  resources :friend_requests, only: [:create] do
    member do
      put :accept
      delete :reject
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :messages, only: [:create, :show, :index] do
    member do
      patch :mark_as_read
    end
  end

  resources :comments, path: "community/:community_id/comments/", only: [:show]

  resources :comments, only: [:create, :destroy], defaults: { commentable: 'post' } do
    resources :comments, only: [:create, :destroy, :show], defaults: { commentable: 'comment' } do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :visits, only: [:index] do
    get 'read', to: 'visits#read'
  end
  resources :prohibited_words, except: [:show]
  resources :admin_messages

  get 'friendrequest_sent/:id', to: 'friend_requests#sent', as: 'friendrequest_sent'

  get "notifications", to: "notifications#index"
  get "my_page", to: "users#my_page"
  get 'all_content', to: 'all_content#index'
  get "/admin/posts", to: "admins#posts"
  get "/admin/communities", to: "admins#communities"
  get "/admin/events", to: "admins#events"
  get "/admin/users", to: "admins#users"
  get "/admin/diaries", to: "admins#diaries"
  get "/admin/pets", to: "admins#pets"
  get "/admin/categories", to: "admins#categories"
  get "/admin/prohibited_words", to: "admins#prohibited_words"
  get "/admin/messages", to: "admins#messages", as: "admin_notifications"

  get "/my_events", to: "events#my_events"
  get "/all_events", to: "events#all_events"
  get "/all_posts", to: "posts#all_posts"
  get "/my_posts", to: "posts#my_posts"
  get "/confirmation_page", to: "home#confirmation", as: "confirmation_page"
  get "/notification/:id", to: "notifications#mark_as_read", as: "notification"

  get '/additional_info', to: 'users#additional_info'
  post '/save_additional_info', to: 'users#save_additional_info'

  get '/edit_community_image/:id', to: 'communities#edit_community_image', as: 'edit_community_image'
  get '/edit_post_image/:id', to: 'posts#edit_post_image', as: 'edit_post_image'
  get '/edit_event_image/:id', to: 'events#edit_event_image', as: 'edit_event_image'

  
  get "company", to: "company#index"
  get "terms", to: "terms#index"
  get "policy", to: "policy#index"
  get "regarding", to: "regarding#index"
  get "contact", to: "contact#index"
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories, dependent: :destroy
    has_many :questions, through: :subcategories
    has_many :communities
    validates_presence_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @subcategory = @category.subcategories.build
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category)}
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category) }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container mt-4" style="max-width: 500px;">
  <h3 class="d-flex align-items-center gap-2 fw-bold mb-4"><i class="fa fa-paw text-main"></i> カテゴリ情報</h3>
  <%= form_with(model: category) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field mb-3">
      <%= form.label :名前, class:"form-label" %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="actions mb-3 text-center">
      <%= form.submit "保存", class: "btn bg-main text-white fw-bold px-5" %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1 align="center">カテゴリー</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>カテゴリー名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to '詳細', category %></td>
        <td><%= link_to '編集', edit_category_path(category) %></td>
        <td><%= link_to '削除', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しいカテゴリーを追加する', new_category_path %>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="container mt-4" style="max-width: 500px">
  <!-- Category Show Page -->
  <h3 class="d-flex align-items-center gap-2 fw-bold mb-4 justify-content-center"><i class="fa fa-paw text-main"></i> <%= @category.name %></h3>
  <div class="mt-5">
    <!-- Subcategory Creation Form -->
    <h5 class="d-flex align-items-center gap-2 fw-bold mb-4"><i class="fa fa-paw text-main"></i> サブカテゴリの追加</h5>
    <%= form_for [@category, @subcategory] do |f| %>
      <!-- Subcategory Name -->
      <div class="mb-3">
        <%= f.label :name, "サブカテゴリ名", class: "mb-2" %>
        <%= f.text_field :name, id: "subcategory-name", class: "form-control" %>
      </div>
      <!-- Submit Button -->
      <div class="mt-4 text-center">
        <%= f.submit "サブカテゴリの作成", class: "btn bg-main text-white fw-bold" %>
      </div>
    <% end %>
    <!-- List of Subcategories -->
    <div class="mt-5">
      <h5 class="d-flex align-items-center gap-2 fw-bold mb-4 justify-content-center"><i class="fa fa-paw text-main"></i> サブカテゴリー</h5>
      <ul>
        <% @category.subcategories.each do |subcategory| %>
          <li><%= subcategory.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>